import type { CSSProperties } from "react";

export const sx: Record<string, CSSProperties> = {
  side: { width:280, height:"100%", flexShrink:0,
    background:"rgba(10,12,20,0.72)", backdropFilter:"blur(18px)",
    borderRight:"1px solid var(--line)", padding:"18px 14px",
    display:"flex", flexDirection:"column", gap:16 },
  brand: { display:"flex", alignItems:"center", gap:10, padding:"4px 6px" },
  brandName: { fontSize:14, fontWeight:700, letterSpacing:4, fontFamily:"'JetBrains Mono',monospace" },
  brandSub: { fontSize:9, color:"var(--ink-3)", letterSpacing:3, fontFamily:"'JetBrains Mono',monospace" },
  newBtn: { display:"flex", alignItems:"center", gap:10, padding:"10px 12px",
    background:"rgba(242,255,43,0.06)", border:"1px solid rgba(242,255,43,0.35)",
    color:"var(--ink-0)", borderRadius:8, cursor:"pointer", fontSize:13, fontWeight:500,
    transition:"all 0.15s" },
  kbd: { marginLeft:"auto", fontSize:10, color:"var(--ink-3)", fontFamily:"'JetBrains Mono',monospace",
    border:"1px solid var(--line)", padding:"2px 6px", borderRadius:4 },
  sideSection: { display:"flex", flexDirection:"column", gap:8, overflow:"hidden" },
  sideHead: { display:"flex", justifyContent:"space-between", padding:"0 6px",
    fontSize:10, letterSpacing:3, color:"var(--ink-3)", fontFamily:"'JetBrains Mono',monospace" },
  convo: { display:"flex", alignItems:"center", gap:10, padding:"8px 10px", background:"transparent",
    border:"1px solid transparent", borderRadius:6, color:"var(--ink-1)", fontSize:12,
    cursor:"pointer", textAlign:"left" },
  convoActive: { background:"rgba(242,255,43,0.05)", border:"1px solid rgba(242,255,43,0.2)", color:"var(--ink-0)" },
  convoDot: { width:5, height:5, borderRadius:99, flexShrink:0 },
  convoTitle: { flex:1, overflow:"hidden", textOverflow:"ellipsis", whiteSpace:"nowrap" },
  convoTime: { fontSize:10, color:"var(--ink-3)", fontFamily:"'JetBrains Mono',monospace" },
  shield: { color:"var(--neon)", fontSize:10, filter:"drop-shadow(0 0 4px rgba(242,255,43,0.6))" },
  vendCard: { padding:14, borderRadius:10,
    background:"linear-gradient(180deg, rgba(242,255,43,0.08), rgba(242,255,43,0.02))",
    border:"1px solid rgba(242,255,43,0.2)" },
  live: { display:"flex", alignItems:"center", gap:6, fontSize:9,
    fontFamily:"'JetBrains Mono',monospace", letterSpacing:2, color:"var(--neon)" },
  liveDot: { width:6, height:6, borderRadius:99, background:"var(--neon)",
    boxShadow:"0 0 8px var(--neon)", animation:"pulse 1.5s infinite" },
  meter: { marginTop:10, height:4, background:"rgba(255,255,255,0.06)", borderRadius:99, overflow:"hidden" },
  meterBar: { height:"100%", background:"var(--neon)", boxShadow:"0 0 8px var(--neon)" },
  userRow: { display:"flex", alignItems:"center", gap:10, marginTop:12, padding:"8px 6px",
    borderTop:"1px solid var(--line)" },
  avatar: { width:28, height:28, borderRadius:8, background:"linear-gradient(135deg,#f2ff2b,#eaff48)",
    color:"#000", display:"flex", alignItems:"center", justifyContent:"center", fontWeight:700, fontSize:11 },
  iconBtn: { background:"transparent", border:"1px solid var(--line)", color:"var(--ink-1)",
    width:28, height:28, borderRadius:6, cursor:"pointer", fontSize:12 },

  topbar: { height:52, display:"flex", alignItems:"center", justifyContent:"space-between",
    padding:"0 22px", borderBottom:"1px solid var(--line)",
    background:"rgba(5,6,10,0.5)", backdropFilter:"blur(20px)",
    position:"relative", zIndex:10 },
  chevron: { color:"var(--ink-3)" },
  modelPill: { display:"flex", alignItems:"center", gap:10, padding:"6px 12px",
    background:"rgba(255,255,255,0.04)", border:"1px solid var(--line)", borderRadius:99,
    color:"var(--ink-0)", fontSize:12, cursor:"pointer" },
  modelCtx: { fontSize:10, color:"var(--ink-3)", fontFamily:"'JetBrains Mono',monospace",
    border:"1px solid var(--line)", padding:"1px 6px", borderRadius:4 },
  modelMenu: { position:"absolute", top:"calc(100% + 8px)", left:"50%", transform:"translateX(-50%)",
    width:420, background:"rgba(16,19,28,0.95)", backdropFilter:"blur(24px)",
    border:"1px solid var(--line)", borderRadius:12,
    boxShadow:"0 20px 60px rgba(0,0,0,0.6), 0 0 0 1px rgba(242,255,43,0.05)",
    zIndex:100, overflow:"hidden" },
  modelMenuHead: { padding:"12px 14px", display:"flex", justifyContent:"space-between",
    fontSize:11, color:"var(--ink-2)", borderBottom:"1px solid var(--line)" },
  provHead: { display:"flex", alignItems:"center", gap:8, fontSize:10, letterSpacing:3,
    color:"var(--ink-3)", fontFamily:"'JetBrains Mono',monospace", padding:"6px 0" },
  modelRow: { display:"flex", alignItems:"center", gap:10, width:"100%", padding:"8px 10px",
    background:"transparent", border:"1px solid transparent", borderRadius:6,
    color:"var(--ink-1)", cursor:"pointer", fontSize:12, textAlign:"left" },
  modelRowActive: { background:"rgba(242,255,43,0.06)", border:"1px solid rgba(242,255,43,0.2)", color:"var(--ink-0)" },
  flash: { fontSize:10, color:"var(--neon)", fontFamily:"'JetBrains Mono',monospace", letterSpacing:1 },
  modelCtxSm: { fontSize:10, color:"var(--ink-3)", fontFamily:"'JetBrains Mono',monospace", width:44, textAlign:"right" },
  modelFoot: { display:"flex", justifyContent:"space-between", padding:"10px 14px",
    fontSize:10, color:"var(--ink-3)", borderTop:"1px solid var(--line)", fontFamily:"'JetBrains Mono',monospace" },

  vendBtn: { display:"flex", alignItems:"center", gap:8, padding:"6px 12px",
    background:"rgba(242,255,43,0.06)", border:"1px solid rgba(242,255,43,0.3)",
    borderRadius:99, fontSize:10, letterSpacing:2,
    fontFamily:"'JetBrains Mono',monospace", color:"var(--ink-0)", cursor:"pointer" },
  vendDot: { width:6, height:6, borderRadius:99, background:"var(--neon)",
    boxShadow:"0 0 10px var(--neon)", animation:"pulse 1.5s infinite" },

  vPanel: { position:"fixed", top:52, right:0, bottom:0, width:360,
    background:"rgba(10,12,20,0.88)", backdropFilter:"blur(24px)",
    borderLeft:"1px solid rgba(242,255,43,0.2)",
    transition:"transform 0.35s cubic-bezier(.2,.9,.3,1.1)",
    zIndex:50, display:"flex", flexDirection:"column",
    boxShadow:"-20px 0 60px rgba(0,0,0,0.5)" },
  vHead: { display:"flex", justifyContent:"space-between", alignItems:"center",
    padding:18, borderBottom:"1px solid var(--line)" },
  vBadge: { width:32, height:32, borderRadius:8,
    background:"radial-gradient(circle at 30% 30%, rgba(242,255,43,0.3), transparent 70%)",
    border:"1px solid rgba(242,255,43,0.5)", color:"var(--neon)",
    display:"flex", alignItems:"center", justifyContent:"center",
    fontWeight:700, position:"relative", fontFamily:"'JetBrains Mono',monospace" },
  vBadgeDot: { position:"absolute", top:-2, right:-2, width:8, height:8, borderRadius:99,
    background:"var(--neon)", boxShadow:"0 0 8px var(--neon)", animation:"pulse 1.5s infinite" },
  vStats: { display:"grid", gridTemplateColumns:"repeat(3,1fr)", gap:1, padding:0,
    borderBottom:"1px solid var(--line)", background:"var(--line)" },
  vStat: { padding:"14px 16px", background:"rgba(10,12,20,0.5)" },
  vStatNum: { fontSize:22, fontWeight:300, fontFamily:"'Instrument Serif',serif", color:"var(--neon)" },
  vStatLbl: { fontSize:9, letterSpacing:2, color:"var(--ink-3)", marginTop:2, fontFamily:"'JetBrains Mono',monospace" },
  aliasToggle: { display:"flex", gap:4, padding:4, marginTop:14,
    background:"rgba(255,255,255,0.03)", borderRadius:8, border:"1px solid var(--line)" },
  aliasTab: { flex:1, padding:"6px 8px", background:"transparent", border:"none",
    borderRadius:6, fontSize:11, color:"var(--ink-2)", cursor:"pointer" },
  aliasTabOn: { background:"rgba(242,255,43,0.12)", color:"var(--neon)" },
  vList: { flex:1, overflow:"auto", padding:"14px 18px" },
  vEmpty: { padding:"20px 4px", textAlign:"left" },
  vGroup: { marginBottom:18 },
  vGroupHead: { display:"flex", alignItems:"center", gap:8, fontSize:10, letterSpacing:2,
    color:"var(--ink-2)", fontFamily:"'JetBrains Mono',monospace", marginBottom:8 },
  vDotNeon: { width:5, height:5, borderRadius:99, background:"var(--neon)",
    boxShadow:"0 0 6px var(--neon)" },
  vItem: { display:"flex", alignItems:"center", gap:8, padding:"8px 10px",
    background:"rgba(255,255,255,0.02)", border:"1px solid var(--line)",
    borderRadius:6, marginBottom:4, fontSize:11, fontFamily:"'JetBrains Mono',monospace" },
  vItemRaw: { flex:1, color:"var(--ink-1)", overflow:"hidden", textOverflow:"ellipsis", whiteSpace:"nowrap" },
  vItemArrow: { color:"var(--ink-3)" },
  vItemAlias: { color:"var(--neon)", textShadow:"0 0 8px rgba(242,255,43,0.4)" },
  vFoot: { padding:"14px 18px", borderTop:"1px solid var(--line)" },
};
